# -*- coding: utf-8 -*-
"""jeju_cctv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PkUVnd1edzmLaDVssgzTLwCZDLJT0tp-
"""

import folium
from folium import Marker, Icon
import pandas as pd
import csv, time

jeju= pd.read_csv('./jeju.csv', encoding='cp949')
jeju.head()

df_sample = jeju[['카메라대수','위도','경도']]
# display(df_sample.head(3))
print('데이터 널값 확인')
display(df_sample.isnull().sum())

loc=[33.37860539157057, 126.52645770837371]
map = folium.Map(loc,   tiles='Stamen Terrain', zoom_start=11)
for i in range(len(jeju)):
  folium.Marker(location=[jeju.loc[i]['위도'],jeju.loc[i]['경도']],
                tooltip=jeju.loc[i]['카메라대수'],
                icon = folium.Icon(color='green', icon="info-sign")
                ).add_to(map)
map.save('jeju.html')
map